services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  transactionsdb:
    container_name: transactionsdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: transactionsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  blacklistdb:
    container_name: blacklistdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: blacklistdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      transactionsdb:
        condition: service_healthy
      blacklistdb:
        condition: service_healthy
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "yoramnagdocker/configserver:0.0.2-SNAPSHOT"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "yoramnagdocker/eurekaserver:0.0.1-SNAPSHOT"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"


  black-list:
    image: "yoramnagdocker/black-list-service:0.0.6-SNAPSHOT"
    container_name: black-list-ms
    ports:
      - "8000:8000"
    healthcheck:
      test: "curl --fail --silent localhost:8000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "black-list-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://blacklistdb:3306/blacklistdb"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  transactions:
    image: "yoramnagdocker/transactions-service:0.0.6-SNAPSHOT"
    container_name: transactions-ms
    ports:
      - "8100:8100"
    healthcheck:
      test: "curl --fail --silent localhost:8100/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "transactions-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://transactionsdb:3306/transactionsdb"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gatewayserver:
    image: "yoramnagdocker/gatewayserver:0.0.2-SNAPSHOT"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      black-list:
        condition: service_healthy
      transactions:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  creditCard:
    driver: "bridge"
